### PR TITLE
Update submission_file.txt

### PR DESCRIPTION
**Pull request by VadimKachevski**
https://github.com/VadimKachevski/OOP_Ex2.git
9d42a60758369202737f8b03af55248a0c8590bc
321711061

### CODE REVIEW

**Comment by Avielyo10** [comment]
@VadimKachevski 
You did well but you need to change your layout, see https://github.com/Avielyo10/oop-verifier/pull/1/checks, change your layout here https://github.com/VadimKachevski/OOP_Ex2.git according to [the this README section](https://github.com/Avielyo10/oop-verifier#move-to-java-layout---using-simple-directory-structure-1st-method).

**Comment by VadimKachevski** [comment]
> @VadimKachevski
> You did well but you need to change your layout, see https://github.com/Avielyo10/oop-verifier/pull/1/checks, change your layout here https://github.com/VadimKachevski/OOP_Ex2.git according to [the this README section](https://github.com/Avielyo10/oop-verifier#move-to-java-layout---using-simple-directory-structure-1st-method).

I changed to the java layout according to the readme, but the test still fails as it tries to open Ex1 folder, but im pretty sure we are on Ex2 at the moment.

**Comment by Avielyo10** [comment]
@VadimKachevski 
All of your code needs to be on the same repository, you are missing Ex1

**Comment by Avielyo10** [comment]
@VadimKachevski 
I believe you meant `implementation 'com.googlecode.json-simple:json-simple:1.1.1'`?

**Comment by Avielyo10** [comment]
@VadimKachevski your package needs to be Ex1 [here](https://github.com/VadimKachevski/OOP_Ex2/blob/master/src/main/java/Ex1/ComplexFunction.java#L1), in all of your files.
I've fixed the issues on my end.

**Comment by VadimKachevski** [comment]
> @VadimKachevski your package needs to be Ex1 [here](https://github.com/VadimKachevski/OOP_Ex2/blob/master/src/main/java/Ex1/ComplexFunction.java#L1), in all of your files.
> I've fixed the issues on my end.

So just to make sure before I commit more, I don't need make package main.java.Ex1 and all the other class in packages, i need to create folders without making them packages? 
Thanks.

**Comment by Avielyo10** [comment]
@VadimKachevski 
Your layout is now great, just rename `package main.java.Ex1;` to `package Ex1;`
And on resources `implementation 'com.googlecode.json-simple:json-simple:1.1.1'`

**Comment by Avielyo10** [comment]
Also [here](https://github.com/VadimKachevski/OOP_Ex2/blob/master/src/test/java/Ex1/ComplexFunctionTest.java#L1) just `package Ex1;`.
Take a look on [`dummy`](https://github.com/Avielyo10/oop-dummy).

**Comment by Avielyo10** [comment]
@VadimKachevski Also remove this [line](https://github.com/VadimKachevski/OOP_Ex2/blob/master/src/main/java/Ex1/Polynom.java#L7) since it's on the same package. 
> So just to make sure before I commit more, I don't need make package main.java.Ex1 and all the other class in packages, i need to create folders without making them packages?
Thanks.  

There is no special thing about package, it's just a directory.
I had a typo, please pull the changes and rename `submition_file.txt` to `submission_file.txt`

**Pull request closed without merging**
